//The guessing project in C++ is a game designed to test the player's luck and knowledge. The player needs to guess a random number generated by the computer. If the player guesses right, they will win a certain amount of money. The winning prize depends on the difficulty of the game. The program implements classes, functions, and user-defined data types. It also uses other features such as loops and conditionals to create a logical structure. Furthermore, it makes use of the standard template library to implement basic operations and other data structures.


#include <iostream>
#include <format>
#include <vector>
#include <cstdlib> //rand()
#include <ctime> //time()

struct diff {
    std::string name;
    int count;
    int prize;
};
typedef std::vector<diff> difficulty;

difficulty createModes(){

    diff easy;
    easy.name = "Easy";
    easy.count = 5;
    easy.prize = 10;
    diff medium;
    medium.name = "Medium";
    medium.count = 10;
    medium.prize = 50;
    diff hard;
    hard.name = "Hard";
    hard.count = 100;
    hard.prize = 1000;

    difficulty mode = {easy,medium,hard};
    return mode;
}

std::string ChooseDifficulty(difficulty modes){
    bool condition = true;
    std::string choice;
    while (condition){
        for (int i=0;i<modes.size();i++){
            std::string text = std::format("[{}] : [{}]\n",modes.at(i).name,modes.at(i).count);
            std::cout << text;
        }
        std::cout << "Choose your difficulty: ";
        std::cin >> choice;
        if ((choice=="Easy") || (choice=="Medium") || (choice=="Hard")){
            condition = false;
        } else {
            std::cout << "Wrong choice of difficulty!\nTry again!\n";
        }
    }
    return choice;
}


int UserNumber(std::string choice,difficulty diff){
    int userChoice;
    int number;
    int j;
    for (int i=0; i<diff.size();i++){
        if (diff.at(i).name==choice){
            number = diff.at(i).count;
            j = i;
        }
    }
    std::string text = std::format("Choose the number between: 1 and {}\nOr choose 0 if u want to end the game.\nChoose: ",diff.at(j).count);
    std::cout << text;
    std::cin >> userChoice;
    return userChoice;
}

int ComputerNumber(std::string choice, difficulty diff){
    srand(time(0));
    int computerChoice;
    int number;
    for (int i=0;i<diff.size();i++){
        if (diff.at(i).name == choice){
            number = diff.at(i).count;
        }
    }
    computerChoice = rand() % number; 
    return computerChoice;
}


int CheckWinner(std::string choice, difficulty diff,int computerNumber,int userNumber){
    int number;
    int prize;
    if (userNumber==computerNumber){
        std::cout<<"You guessed the right number!\n";
        for (int i=0;i<diff.size();i++){
            if (choice == diff.at(i).name){
                prize = diff.at(i).prize;
            }
        }
    } else {
        std::cout << "You guessed wrong!\n";
        std::cout << std::format("Computers choice was: {}\n",computerNumber);
        prize = 0;
    } 
    return prize;
}



void GameLoop(difficulty diff){
    std::string choice = ChooseDifficulty(diff);
    bool condition = true;
    int moneyPool = 0;
    while (condition){
        int userNumber = UserNumber(choice,diff);
        if (userNumber == 0){
            condition = false;
        } else {
            int computerNumber = ComputerNumber(choice,diff);
            int prize = CheckWinner(choice, diff, computerNumber, userNumber);
            moneyPool += prize;
            std::cout << std::format("Your current prize: {}\n",moneyPool);
            std::cout << "= = = = = = = = = = = = = = = = = = = = = = = = =\n";
        }
    }
}



int main(){
    difficulty modes = createModes();
    GameLoop(modes);

    return 0;
}






